### ISSUE TITLE
COE - Taliban Compat no scenario

### ISSUE THREAD

**Issue by MikeMasters** [Kexanone/CombatOpsEnhanced_AR#49]
There is no scenario available to play against the taliban in the mission maker. Is it possible to make a mission maker for US VS Taliban?

**Comment by Kexanone** [comment]
Taliban compat just overrides `{02D590EBF5578568}Configs/Missions/COE_Kunar_US.conf` and `{5DCCDAB5717AE362}Configs/Missions/COE_Kunar_USSR.conf`, so if you play them, you'll automatically get Taliban as opposing faction.
