### ISSUE TITLE
RHS Compat

### ISSUE THREAD

**Issue by SD-Arwed** [Kexanone/CombatOpsEnhanced_AR#51]
Hello Thx for your Work ,
there is a bug in the RHS Compat you cant spawn a Vehicle when you play as RHS Soldier, i think its Faction related.
It is possible to change the Humvees on Kunar to the Oliv Version so we can use Tan Humvees .
https://reforger.armaplatform.com/workshop/605CD73327B71AD6-TanHumvees

Greetings from Germany 
Arwed

**Comment by Kexanone** [comment]
The vehicle request system is the same as in Conflict. Hence, the corresponding assets mods like RHS have to be properly configured, which they haven't done yet.

**Comment by Kexanone** [comment]
Closed as needs to be fixed on RHS' end.

**Comment by SD-Arwed** [comment]
thx

**Comment by Kexanone** [comment]
Superseded by https://github.com/RHSMODS/statusquo/issues/769
