### ISSUE TITLE
Vehicle keep getting deleted

### ISSUE THREAD

**Issue by Thedabking710** [Kexanone/CombatOpsEnhanced_AR#52]
Vehicles I take to a mission get deleted. Not sure if it’s a COE issue or just with the Kunar version of COE.

**Comment by Kexanone** [comment]
It's caused by the base game garbage system. You can use this mod to override it: https://reforger.armaplatform.com/workshop/60E2D7E5A20FABEB

**Comment by Thedabking710** [comment]
Thank you so much!
